TOKEN = "token"
PREFIX = "cb/"
OWNER_IDS = [1, 2, 3]

[database]
# all options defined here are passed to asyncpg.create_pool
host = "ip here"
database = "db name"
password = "password"
user = "username"

[jishaku]
# optional - all flags defined here are set by the bot
JISHAKU_NO_UNDERSCORE = true
JISHAKU_NO_DM_TRACEBACK = true
